### ISSUE TITLE
add seralization for std::optional and std::variant

### ISSUE THREAD

**Issue by ibmibmibm** [boostorg/serialization#114]
We need a serialization function for std::optional and std::variant.
Maybe they can be placed in `boost/serialization/optional.hpp`, the file for boost::optional and `boost/serialization/variant.hpp` for boost::variant, or new header files?

**Comment by ibmibmibm** [comment]
std::optional and std::variant are c++17 only, so it can be implemented in c++17.

**Comment by PhilippMuenzel** [comment]
I have the same problem. 
I have to decide now whether I go with std::variant in a new piece of code I'm writing right now for C++17 (so backward compatibility with older compilers is not an issue for this piece of code) or still use boost::variant. I found that the only dependency that keeps me from using std::variant all the way is the ability to boost::serialize it. 

I can hack my own crude serialization for the _specific_ variants I'm using, but I'm not enough of an MPL to template metaprogramming wizard to implement serialization of a generic variant. 

So now the question is to use boost::variant or std::variant+"kludge", in the hope of being able to remove "kludge" some day - whether and when this day comes is the variable on which the decision depends.

**Comment by robertramey** [comment]
Traditionally, we've implemented serialization for standard library types within the serialization libraries and for boost library types within the particular boost library.  This is done in order to prevent the obligations of being the boost serialization library maintainer from growing beyond what I can do.  As the standard library keeps importing more boost stuff and creating more stuff, it's hard to keep up with just the standard library.

For some reason long, long ago, I put serialization of boost::optional and boost::variant into the serialization library.  Now that the standard has incorporated their own versions of these libraries things could get pretty confusing.  So what I believe that the current implementations of variant and optional should be moved to their own boost/variant and boost/optional libraries and new versions for the std::variant and std::optional should be placed in the boost serialization library.

Make the move is not too difficult.  But even that is a pain.  The tests should be moved as well.

But then there is the question of implementation of the new libraries.  One could start modifying the current implementations for boost.  But I'm pretty sure their would be more.  The Committee likes to take a boost library and "improve" it so that it's only mostly compatible.  Also, the implementations could make use of more recent versions of C++.  In particular the implementation of boost::variant supports MSVC going back to version 6.0 - very, very, old.  I'm sure implementation could be better today.  Of course this means tweaking the test Jamfile so that the tests for these libraries are run only for more recent compilers.

So this seemingly trivial task turns into the usual can of worms.  I don't know when I'll get to it.  If anyone want's to do it, I recommend that he:

a) fork the library
b) add your implementation to the code
c) update the documentation
d) add a test of serialization

create a pull request.

What's in it for you?

a) you get the enhancement to the library that you need.
b) you get can put your name on the copyright of the serialization code and the test and a note in the documentation.
c) so you can proudly wear the title of official boost library maintainer - which can look good on your resume,
d) the eternal gratitude of those who come after you.

**Comment by Winklbauer** [comment]
Any update. I am using C++17 structures. We use boost::serialization, but it is getting less easy to use due to lack of support for more modern standard containers like the ones above. C++17 was 2 years ago. Still not supported. Soon we have to look for replacements as it is a lot of overhead to hack support into.

**Comment by egorpugin** [comment]
+1

**Comment by robertramey** [comment]
anyone is free to implement it and post it as  a PR.  I think I have a good record of accepting such contributions while at the same time maintaining a high standard.  It's not as easy at it looks.

**Comment by PhilippMuenzel** [comment]
what's the status of the open pull request(s)? Are they unacceptable? Should we use a fork with the PR merged in to move forward?

**Comment by robertramey** [comment]
I'll look this weekend

**Comment by hdclark** [comment]
Support for std::variant is a feature I'm eagerly awaiting as well. @robertramey is there anything I can do to help unstick this?

**Comment by nightsparc** [comment]
Is there any progress so far regarding std::variants inclusion? :)

**Comment by Febbe** [comment]
Push, this is already one year old, and no one implemented this.

**Comment by demihamster** [comment]
For anyone looking for a quick workaround for serializing std::variant (std::optional should be conceptually the same), this works for me:

```
namespace boost
{
	namespace serialization
	{
		template <class Archive, typename ...Ts>
		void save(Archive& ar, const std::variant<Ts...>& obj, const unsigned int version)
		{
			boost::variant<Ts...> v;
			std::visit([&](const auto& arg) {
				v = arg; 
			}, obj);

			ar & v;
		}

		template <class Archive, typename ...Ts>
		void load(Archive& ar, std::variant<Ts...>& obj, const unsigned int version)
		{
			boost::variant<Ts...> v;
			ar& v;

			boost::apply_visitor([&](auto& arg) {
				obj = arg;
			}, v);
		}

		template <class Archive, typename ...Ts>
		void serialize(Archive& ar, std::variant<Ts...>& t, const unsigned int file_version)
		{
			split_free(ar, t, file_version);
		}
	}
}
```

However please note that it still may not work as there is some bug with tracking memory for boost::variant #203 .
I serialize variants with PODs, so I overrode the header boost/serialization/variant.hpp line 
`typedef mpl::int_< ::boost::serialization::track_always> type;`
to
`typedef mpl::int_< ::boost::serialization::track_never> type;`

and now I have correctly serialized std::variant with pod types. I don't know whether it will work for objects that need tracking

**Comment by kilasuelika** [comment]
For those who need this, please check @sdebionne 's [std_variant.hpp](https://github.com/boostorg/serialization/pull/148). It runs smoothly on my test though I don't know why it's not merged.

**Comment by edisonhello** [comment]
Push. Looking forward to seeing this get merged.

**Comment by mbUSC** [comment]
This is sad :(

**Comment by PhilippMuenzel** [comment]
Just move on. Cereal supports variant and optional since 2019 (v1.3.0).
Don't waste your time with unmaintained abandonware.
