### ISSUE TITLE
collection_size_type copy.hpp: The first header filename w/ a space in the name?

### ISSUE THREAD

**Issue by zaufi** [boostorg/serialization#221]
Hi,

I've thought the [filenames w/ spaces](https://github.com/boostorg/serialization/blob/develop/include/boost/serialization/collection_size_type%20copy.hpp) (especially headers) are prohibited in Boost libraries... Anything has changed?

BTW, I don't see any usage of this file in the code...

**Comment by psigen** [comment]
@zaufi it looks like this was simply an accidentally (auto-renamed) copy of the other file that was accidentally commited:

https://github.com/boostorg/serialization/commit/07c99b8649d7bb900271ca93ba3eea9dcb478f42#diff-c7259865ae65dd94c715482e2abf4fbb3ee9f77e63eb1b6677eada21bd239b08

It's been removed from the repo, so I think this is resolved, we just need to wait for the next release cycle.

**Comment by vervaekejonathan** [comment]
This file is still present in the latest (1.82.0) version downloaded here: https://boostorg.jfrog.io/artifactory/main/release/1.82.0/source/boost_1_82_0.tar.gz

**Comment by sfc-gh-ebrossard** [comment]
The file has been deleted since 1.84, so this can be closed. https://github.com/boostorg/serialization/tree/boost-1.84.0/include/boost/serialization

**Comment by gennaroprota** [comment]
Thanks everyone. Closing.
